# This is the network config written by 'subiquity'
network:
  renderer: networkd
  ethernets:
    ens160:
      addresses:
        - 10.30.3.10/24
      nameservers:
        addresses: [10.220.3.20,10.200.0.20]
      routes:
        - to: default
          via: 10.30.3.1
  version: 2
