# This is the network config written by 'subiquity'
network:
version: 2
ethernets:
ens160:
addresses: [10.30.3.40/24]
gateway4: 10.30.3.1
nameservers:
addresses: [10.220.3.20, 10.220.0.20]
#Hecho por Ivan Diaz Fernandez y descargado de https://github.com/ivaandf/ipcambiante.git
#Actualizado a 20/11/2023 segun directrices del manual del Vcenter del CIFP de Aviles.
