# This is the network config written by 'subiquity'
network:
  ethernets:
    ens160:
      addresses:
      - 192.168.100.110/24
      dhcp4: false
      routes:
        - to: default
          via: 192.168.100.1
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
  version: 2
#Hecho por Ivan Diaz Fernandez y descargado de https://github.com/ivaandf/ipcambiante.git